# command
GO=go
GO_CMD=GO111MODULE=on
GO_VET=$(GO) vet
GO_BUILD=$(GO) build
GO_IMPORTS=goimports
GO_FMT=gofmt
GO_CTL=goctl

# path
MAKEFILE_PATH=$(abspath $(lastword $(MAKEFILE_LIST)))
MAKEFILE_DIR=$(abspath $(dir $(MAKEFILE_PATH)))
CURRENT_PATH=$(MAKEFILE_DIR)
ROOT_PATH=$(abspath $(CURRENT_PATH)/../)

PROJECT_ROOT_PATH=$(MYSQLDOC_PATH)
# 服务端根目录绝对路径
SRC_PATH=$(PROJECT_ROOT_PATH)/src
# 服务端存放前端文件根目录绝对路径
GO_UI_PATH=$(SRC_PATH)/ui
# 前端根目录绝对路径
UI_PATH=$(PROJECT_ROOT_PATH)/ui
# 服务端打包输出路径
OUT_PATH=$(PROJECT_ROOT_PATH)/mysqldoc-out

BIN_NAME=mysqldoc
MAIN_GO_FILE_NAME=mysqldoc.go

# platform
DARWIN_BIN_NAME=$(BIN_NAME)-darwin
WINDOWS_BIN_NAME=$(BIN_NAME).exe
LINUX_BIN_NAME=$(BIN_NAME)-linux

BUILD_BIN_PATH=$(OUT_PATH)/$(BIN_NAME)
DARWIN_BIN_PATH=$(OUT_PATH)/$(DARWIN_BIN_NAME)
WINDOWS_BIN_PATH=$(OUT_PATH)/$(WINDOWS_BIN_NAME)
LINUX_BIN_PATH=$(OUT_PATH)/$(LINUX_BIN_NAME)

BUILD_PARAMS=CGO_ENABLED=0 GOARCH=arm64

# upx
IF_UPX= $(shell command -v upx)
BUILD_UPX=$(if $(IF_UPX), upx $(BUILD_BIN_PATH))
DARWIN_UPX=$(if $(IF_UPX), upx $(DARWIN_BIN_PATH))
WINDOWS_UPX=$(if $(IF_UPX), upx $(WINDOWS_BIN_PATH))
LINUX_UPX=$(if $(IF_UPX), upx $(LINUX_BIN_PATH))